// Authors
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';

// Courses
export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';

// Ajax
export const AJAX_CALL_BEGIN = 'AJAX_CALL_BEGIN';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
